import React from 'react'
import NavLayout from "./NavLayout"
import Head from 'next/head'
import { Container } from "react-bootstrap"
import styles from '../styles/Home.module.css'

export default function Layout({children}) {
  return (
    <>
      <Head>
        <title>Param Cebimde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLayout />
      <Container>
        <main className={styles.main}>
          {children}
          </main>
      </Container>
    </>
  )
}
